# Generated by Django 5.2.8 on 2025-11-19 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object creation datetime.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated datetime.')),
                ('island_name', models.CharField(max_length=255, verbose_name='Island Name')),
                ('description_pt', models.TextField(max_length=3000, verbose_name='Description in Portuguese')),
                ('description_en', models.TextField(max_length=3000, verbose_name='Description in English')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object creation datetime.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated datetime.')),
                ('county_name', models.CharField(max_length=255, verbose_name='County Name')),
                ('description_pt', models.TextField(max_length=3000, verbose_name='Description in Portuguese')),
                ('description_en', models.TextField(max_length=3000, verbose_name='Description in English')),
                ('island', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='islands.island', verbose_name='Island')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object creation datetime.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated datetime.')),
                ('parish_name', models.CharField(max_length=255, verbose_name='Parish Name')),
                ('description_pt', models.TextField(max_length=3000, verbose_name='Description in Portuguese')),
                ('description_en', models.TextField(max_length=3000, verbose_name='Description in English')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='islands.county', verbose_name='County')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
