# Generated by Django 5.2.8 on 2025-11-19 19:07

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=75, scale=None, size=[1024, 768], upload_to='county'),
        ),
        migrations.AddField(
            model_name='island',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=75, scale=None, size=[1024, 768], upload_to='island'),
        ),
        migrations.AddField(
            model_name='parish',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=75, scale=None, size=[1024, 768], upload_to='parish'),
        ),
        migrations.AlterField(
            model_name='county',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='county',
            name='description_pt',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in Portuguese'),
        ),
        migrations.AlterField(
            model_name='island',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='island',
            name='description_pt',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in Portuguese'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='description_pt',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in Portuguese'),
        ),
    ]
